// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0sMx7DkYehMN8gb_USrVCdHo_YuhzoA',
    appId: '1:213205425938:web:9fcfbecd0bc46ce8c8ddcb',
    messagingSenderId: '213205425938',
    projectId: 'fruits-app-74ff2',
    authDomain: 'fruits-app-74ff2.firebaseapp.com',
    storageBucket: 'fruits-app-74ff2.firebasestorage.app',
    measurementId: 'G-F08GFYCR77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA3fGOwF7y3M-yaohhZD3_EB4QiA76wjs',
    appId: '1:213205425938:android:56a61ae2957836dec8ddcb',
    messagingSenderId: '213205425938',
    projectId: 'fruits-app-74ff2',
    storageBucket: 'fruits-app-74ff2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrNHI-yg_VlIu2kaVavFTv2pLftxT-ZiU',
    appId: '1:213205425938:ios:d097e9f45c4ff346c8ddcb',
    messagingSenderId: '213205425938',
    projectId: 'fruits-app-74ff2',
    storageBucket: 'fruits-app-74ff2.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrNHI-yg_VlIu2kaVavFTv2pLftxT-ZiU',
    appId: '1:213205425938:ios:d097e9f45c4ff346c8ddcb',
    messagingSenderId: '213205425938',
    projectId: 'fruits-app-74ff2',
    storageBucket: 'fruits-app-74ff2.firebasestorage.app',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI0sMx7DkYehMN8gb_USrVCdHo_YuhzoA',
    appId: '1:213205425938:web:5895c8289c820db2c8ddcb',
    messagingSenderId: '213205425938',
    projectId: 'fruits-app-74ff2',
    authDomain: 'fruits-app-74ff2.firebaseapp.com',
    storageBucket: 'fruits-app-74ff2.firebasestorage.app',
    measurementId: 'G-PXB10BBG6B',
  );

}